#!/usr/bin/env bash
# Collecting arguments from the command line and use it with the scp command
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
# Assigning the arguments to variables
PATHTOFILE="$1"
IP="$2"
USERNAME="$3"
PATHTOSSHKEY="$4"

# Sending the file to the remote server
scp -o StrictHostKeyChecking=no -i "$PATHTOSSHKEY" "$PATHTOFILE" "$USERNAME"@"$IP":~/
