#!/usr/bin/env bash
# This script configures nginx on our server

# update package lists and install nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Reload nginx configuration
sudo service nginx reload

# Create a simple HTML file with 'Hello World!' Content
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html

# Make sure nginx process is running
if ! pgrep -x "nginx" > /dev/null; then
	sudo service nginx start
fi
