#!/usr/bin/env bash
# This script configures nginx on our server

# update package lists and install nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/ubuntu_nginx_index.html
sudo echo "Hello World!" > /var/www/html/ubuntu_nginx_index.html
sudo service nginx restart
