#!/usr/bin/env bash
# This project writes the PID to a file and deletes the file whilst
#+ terminating the process

# findig the process id and save in PID
PID=$(pgrep -f "100-process_and_pid_file")

# Saving the PID to a file
echo "$PID" > /var/run/myscript.pid

# Commands to be executed when the process receives a sigterm signal
sigterm_handler()
{
	# string to be printed when the process receives a signal
	echo "I hate the kill command"
	
	# deleting the file
	rm -f /var/run/myscript.pid
	# killing the process
	exit 0
}

# Commands to be executed when the process receives the sigint signal
sigint_handler()
{
	# prints these strings when received the sigint signal
	echo "Y U no love me?!"
	exit 0
}

# trapping the process
trap sigint_handler SIGINT
trap sigterm_handler SIGTERM SIGQUIT

# printing the infinite string
while true;
do
	echo "To infinity and beyond"
	sleep 2
done

