#!/usr/bin/env bash
# The sends signal based on the arguments passed with the script

# creating the start process function
start_process()
{
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
}

# creating the stop process function
stop_process()
{
	PID=$(cat /var/run/my_process.pid)
	kill -9 "$PID"
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
}
# creating the restart process function
restart_process()
{
	PID=$(cat /var/run/my_process.pid)
	kill -9 "$PID"
	rm -f /var/run/my_process.pid
	./manage_my_process
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
}

# checking if the argument passed is one of the handlers

if [ "$1" == "start" ]; then
	start_process
elif [ "$1" == "stop" ]; then
	stop_process
elif [ "$1" == "restart" ]; then
	restart_process
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
