#!/usr/bin/env bash
# This project displays PIDs of lines containing the bash word
# shellcheck disable=SC2009

while IFS='' read -r line || [[ -n "$line" ]];
do
	if [[ $line == *"bash"* ]]; then
		echo "$line"
	fi
done < <(ps -aux)
