#!/usr/bin/env bash
# This project displays the time for 12 hours and 59 minutes
hour=0
while ((hour <= 12))
do
	echo "Hour: $hour"
	i=1
	while ((i <= 59))
	do
		echo "$i"
		((i += 1))
	done
	((h += 1))
done
