#!/usr/bin/env bash
# This project distributes the content on each line in /etr/passwd to
# the given replacement fields
IFS=":"

while read -r username groupid home_dict shell user_id passw user_id_info;
do
	echo "The user $username is part of the $groupid gang, lives in\
 $home_dict and rides $shell."
	echo "$user_id's place is protected by the passcode $passw,\
 more info about the user here: $user_id_info"

done < "/etc/passwd"
