#!/usr/bin/env bash
# This project shows us how to print something else at any 
# iteration point
name="Best School"
count=1
while ((count <= 10))
do
	if ((count == 9)); then
		echo "$name"
		echo "Hi"
	else
		echo "$name"
	fi
	count=$((count + 1))
done
