#!/usr/bin/env bash
# This project prints all files and directories in the current 
# directory and extract the second field from each line using 
# the cut command

for f in *;
do 
	echo "$f" | cut -f2 -d"-"
done
