#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# copying the file of ip addresses and host names
cp /etc/hosts ~/hosts.new
# writing the new ip address for the host
echo "127.0.0.2		localhost" > ~/hosts.new
# writing the new ip address for the facebook host
echo "8.8.8.8		facebook.com" >> ~/hosts.new
# copying the new file to the hosts file
cp -f ~/hosts.new /etc/hosts
